<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'name' => 'Devil May Cry 5',
                'slug' => 'devil-may-cry-5',
                'description' => 'Disfruta de Devil May Cry 5, uno de los mejores títulos en la categoría Acción. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '189.00',
                'stock' => 15,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:17:49',
                'deleted_at' => '2026-03-20 05:17:49',
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 1,
                'name' => 'Bayonetta 3',
                'slug' => 'bayonetta-3',
                'description' => 'Disfruta de Bayonetta 3, uno de los mejores títulos en la categoría Acción. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '210.00',
                'stock' => 8,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:17:52',
                'deleted_at' => '2026-03-20 05:17:52',
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 1,
                'name' => 'Metal Gear Rising',
                'slug' => 'metal-gear-rising',
                'description' => 'Disfruta de Metal Gear Rising, uno de los mejores títulos en la categoría Acción. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '120.00',
                'stock' => 20,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:17:54',
                'deleted_at' => '2026-03-20 05:17:54',
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 1,
                'name' => 'Sekiro: Shadows Die Twice',
                'slug' => 'sekiro-shadows-die-twice',
                'description' => 'Disfruta de Sekiro: Shadows Die Twice, uno de los mejores títulos en la categoría Acción. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '230.00',
                'stock' => 12,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:17:55',
                'deleted_at' => '2026-03-20 05:17:55',
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 2,
                'name' => 'The Legend of Zelda: BotW',
                'slug' => 'the-legend-of-zelda-botw',
                'description' => 'Disfruta de The Legend of Zelda: BotW, uno de los mejores títulos en la categoría Aventura. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '270.00',
                'stock' => 10,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:01',
                'deleted_at' => '2026-03-20 05:18:01',
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 2,
                'name' => 'Uncharted 4',
                'slug' => 'uncharted-4',
                'description' => 'Disfruta de Uncharted 4, uno de los mejores títulos en la categoría Aventura. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '150.00',
                'stock' => 18,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:07',
                'deleted_at' => '2026-03-20 05:18:07',
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 2,
                'name' => 'Horizon Forbidden West',
                'slug' => 'horizon-forbidden-west',
                'description' => 'Disfruta de Horizon Forbidden West, uno de los mejores títulos en la categoría Aventura. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '240.00',
                'stock' => 7,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:11',
                'deleted_at' => '2026-03-20 05:18:11',
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 2,
                'name' => 'Kena: Bridge of Spirits',
                'slug' => 'kena-bridge-of-spirits',
                'description' => 'Disfruta de Kena: Bridge of Spirits, uno de los mejores títulos en la categoría Aventura. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '130.00',
                'stock' => 14,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:15',
                'deleted_at' => '2026-03-20 05:18:15',
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 3,
                'name' => 'Elden Ring',
                'slug' => 'elden-ring',
                'description' => 'Disfruta de Elden Ring, uno de los mejores títulos en la categoría RPG. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '250.00',
                'stock' => 20,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:17',
                'deleted_at' => '2026-03-20 05:18:17',
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 3,
                'name' => 'Final Fantasy XVI',
                'slug' => 'final-fantasy-xvi',
                'description' => 'Disfruta de Final Fantasy XVI, uno de los mejores títulos en la categoría RPG. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '280.00',
                'stock' => 9,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:19',
                'deleted_at' => '2026-03-20 05:18:19',
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 3,
                'name' => 'Baldur\'s Gate 3',
                'slug' => 'baldurs-gate-3',
                'description' => 'Disfruta de Baldur\'s Gate 3, uno de los mejores títulos en la categoría RPG. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '260.00',
                'stock' => 11,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:21',
                'deleted_at' => '2026-03-20 05:18:21',
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 3,
                'name' => 'Dragon\'s Dogma 2',
                'slug' => 'dragons-dogma-2',
                'description' => 'Disfruta de Dragon\'s Dogma 2, uno de los mejores títulos en la categoría RPG. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '255.00',
                'stock' => 6,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:32',
                'deleted_at' => '2026-03-20 05:18:32',
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 4,
                'name' => 'EA Sports FC 25',
                'slug' => 'ea-sports-fc-25',
                'description' => 'Disfruta de EA Sports FC 25, uno de los mejores títulos en la categoría Deportes. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '220.00',
                'stock' => 30,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:34',
                'deleted_at' => '2026-03-20 05:18:34',
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 4,
                'name' => 'NBA 2K25',
                'slug' => 'nba-2k25',
                'description' => 'Disfruta de NBA 2K25, uno de los mejores títulos en la categoría Deportes. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '200.00',
                'stock' => 22,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 04:58:20',
                'deleted_at' => '2026-03-20 04:58:20',
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 4,
                'name' => 'Gran Turismo 7',
                'slug' => 'gran-turismo-7',
                'description' => 'Disfruta de Gran Turismo 7, uno de los mejores títulos en la categoría Deportes. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '210.00',
                'stock' => 15,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:36',
                'deleted_at' => '2026-03-20 05:18:36',
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 4,
                'name' => 'WWE 2K24',
                'slug' => 'wwe-2k24',
                'description' => 'Disfruta de WWE 2K24, uno de los mejores títulos en la categoría Deportes. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '190.00',
                'stock' => 12,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:38',
                'deleted_at' => '2026-03-20 05:18:38',
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 5,
                'name' => 'Civilization VII',
                'slug' => 'civilization-vii',
                'description' => 'Disfruta de Civilization VII, uno de los mejores títulos en la categoría Estrategia. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '240.00',
                'stock' => 8,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:40',
                'deleted_at' => '2026-03-20 05:18:40',
            ),
            17 => 
            array (
                'id' => 18,
                'category_id' => 5,
                'name' => 'StarCraft II',
                'slug' => 'starcraft-ii',
                'description' => 'Disfruta de StarCraft II, uno de los mejores títulos en la categoría Estrategia. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '90.00',
                'stock' => 25,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:42',
                'deleted_at' => '2026-03-20 05:18:42',
            ),
            18 => 
            array (
                'id' => 19,
                'category_id' => 5,
                'name' => 'Age of Empires IV',
                'slug' => 'age-of-empires-iv',
                'description' => 'Disfruta de Age of Empires IV, uno de los mejores títulos en la categoría Estrategia. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '170.00',
                'stock' => 13,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:46',
                'deleted_at' => '2026-03-20 05:18:46',
            ),
            19 => 
            array (
                'id' => 20,
                'category_id' => 5,
                'name' => 'XCOM 3',
                'slug' => 'xcom-3',
                'description' => 'Disfruta de XCOM 3, uno de los mejores títulos en la categoría Estrategia. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '160.00',
                'stock' => 10,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:48',
                'deleted_at' => '2026-03-20 05:18:48',
            ),
            20 => 
            array (
                'id' => 21,
                'category_id' => 6,
                'name' => 'Resident Evil 4 Remake',
                'slug' => 'resident-evil-4-remake',
                'description' => 'Disfruta de Resident Evil 4 Remake, uno de los mejores títulos en la categoría Terror. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '230.00',
                'stock' => 17,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:50',
                'deleted_at' => '2026-03-20 05:18:50',
            ),
            21 => 
            array (
                'id' => 22,
                'category_id' => 6,
                'name' => 'Silent Hill 2 Remake',
                'slug' => 'silent-hill-2-remake',
                'description' => 'Disfruta de Silent Hill 2 Remake, uno de los mejores títulos en la categoría Terror. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '245.00',
                'stock' => 9,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:52',
                'deleted_at' => '2026-03-20 05:18:52',
            ),
            22 => 
            array (
                'id' => 23,
                'category_id' => 6,
                'name' => 'Alien: Isolation',
                'slug' => 'alien-isolation',
                'description' => 'Disfruta de Alien: Isolation, uno de los mejores títulos en la categoría Terror. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '100.00',
                'stock' => 20,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:19:02',
                'deleted_at' => '2026-03-20 05:19:02',
            ),
            23 => 
            array (
                'id' => 24,
                'category_id' => 6,
                'name' => 'Outlast Trials',
                'slug' => 'outlast-trials',
                'description' => 'Disfruta de Outlast Trials, uno de los mejores títulos en la categoría Terror. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '120.00',
                'stock' => 14,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:19:04',
                'deleted_at' => '2026-03-20 05:19:04',
            ),
            24 => 
            array (
                'id' => 25,
                'category_id' => 7,
                'name' => 'Microsoft Flight Simulator',
                'slug' => 'microsoft-flight-simulator',
                'description' => 'Disfruta de Microsoft Flight Simulator, uno de los mejores títulos en la categoría Simulación. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '270.00',
                'stock' => 6,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:19:05',
                'deleted_at' => '2026-03-20 05:19:05',
            ),
            25 => 
            array (
                'id' => 26,
                'category_id' => 7,
                'name' => 'Cities: Skylines 2',
                'slug' => 'cities-skylines-2',
                'description' => 'Disfruta de Cities: Skylines 2, uno de los mejores títulos en la categoría Simulación. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '200.00',
                'stock' => 9,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:29',
                'deleted_at' => '2026-03-20 05:18:29',
            ),
            26 => 
            array (
                'id' => 27,
                'category_id' => 7,
                'name' => 'Farming Simulator 25',
                'slug' => 'farming-simulator-25',
                'description' => 'Disfruta de Farming Simulator 25, uno de los mejores títulos en la categoría Simulación. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '180.00',
                'stock' => 11,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:18:58',
                'deleted_at' => '2026-03-20 05:18:58',
            ),
            27 => 
            array (
                'id' => 28,
                'category_id' => 7,
                'name' => 'Planet Zoo',
                'slug' => 'planet-zoo',
                'description' => 'Disfruta de Planet Zoo, uno de los mejores títulos en la categoría Simulación. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '140.00',
                'stock' => 15,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:19:07',
                'deleted_at' => '2026-03-20 05:19:07',
            ),
            28 => 
            array (
                'id' => 29,
                'category_id' => 8,
                'name' => 'Cyberpunk 2077',
                'slug' => 'cyberpunk-2077',
                'description' => 'Disfruta de Cyberpunk 2077, uno de los mejores títulos en la categoría Shooter. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '200.00',
                'stock' => 25,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:19:09',
                'deleted_at' => '2026-03-20 05:19:09',
            ),
            29 => 
            array (
                'id' => 30,
                'category_id' => 8,
                'name' => 'Doom Eternal',
                'slug' => 'doom-eternal',
                'description' => 'Disfruta de Doom Eternal, uno de los mejores títulos en la categoría Shooter. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '130.00',
                'stock' => 18,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:19:11',
                'deleted_at' => '2026-03-20 05:19:11',
            ),
            30 => 
            array (
                'id' => 31,
                'category_id' => 8,
                'name' => 'Borderlands 3',
                'slug' => 'borderlands-3',
                'description' => 'Disfruta de Borderlands 3, uno de los mejores títulos en la categoría Shooter. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '110.00',
                'stock' => 22,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:19:12',
                'deleted_at' => '2026-03-20 05:19:12',
            ),
            31 => 
            array (
                'id' => 32,
                'category_id' => 8,
                'name' => 'Halo Infinite',
                'slug' => 'halo-infinite',
                'description' => 'Disfruta de Halo Infinite, uno de los mejores títulos en la categoría Shooter. Disponible en nuestra tienda con envío a todo Bolivia.',
                'price' => '170.00',
                'stock' => 14,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 03:34:44',
                'updated_at' => '2026-03-20 05:19:14',
                'deleted_at' => '2026-03-20 05:19:14',
            ),
            32 => 
            array (
                'id' => 33,
                'category_id' => 2,
                'name' => 'Cuphead',
                'slug' => 'cuphead',
                'description' => 'Un juego cooperativo con dificultad modificable con una aventura de dos personajes que se enfrentaran a demonios que tu no imaginabas',
                'price' => '90.00',
                'stock' => 9,
                'image_path' => 'products/delxPJcBDtBNBSKwAfXOwXQEK3nfDwuhXxCvRDFW.png',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 04:58:11',
                'updated_at' => '2026-03-20 04:58:35',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'category_id' => 8,
                'name' => 'Halo Infinit',
                'slug' => 'halo-infinit',
                'description' => 'Halo Infinite es un videojuego de disparos en primera persona y mundo abierto de la franquicia de videojuegos de ciencia ficción Halo, creada por Bungie Studios y actualmente desarrollada por 343 Industries. Es exclusivo para las plataformas Xbox One, Microsoft Windows y Xbox Series X|S.',
                'price' => '130.00',
                'stock' => 17,
                'image_path' => 'products/1uF3fasxz7psDt7zxq3Z7kriftzAScGAaIT2MJaX.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:21:33',
                'updated_at' => '2026-03-20 05:22:34',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'category_id' => 8,
                'name' => 'Counter Strike 2',
                'slug' => 'counter-strike-2',
                'description' => 'Counter-Strike 2 es un videojuego de disparos táctico en primera persona multijugador de 2023 desarrollado y publicado por Valve. Es la quinta entrega principal de la serie Counter-Strike.',
                'price' => '70.00',
                'stock' => 19,
                'image_path' => 'products/Q1JlWKtZU7m6WGaZ7TuE2cgBtnE6mP0SkJnUYWTk.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:23:49',
                'updated_at' => '2026-03-20 05:23:49',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'category_id' => 6,
                'name' => 'Phasmophobia',
                'slug' => 'phasmophobia',
                'description' => 'Phasmophobia es un videojuego de terror independiente desarrollado y publicado por Kinetic Games. El juego contó con un acceso anticipado a través de Steam para los equipos de Microsoft Windows en septiembre de 2020, junto con soporte de realidad virtual',
                'price' => '100.00',
                'stock' => 30,
                'image_path' => 'products/1nxiBEA6NUoRzcDaxTNYAaJpDzd4Fmb3X5wxx4Dw.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:24:57',
                'updated_at' => '2026-03-20 13:15:23',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'category_id' => 2,
                'name' => 'The Legend of Zelda: Breath of the Wild',
                'slug' => 'the-legend-of-zelda-breath-of-the-wild',
                'description' => 'The Legend of Zelda: Breath of the Wild es un videojuego de acción-aventura de 2017 de la serie The Legend of Zelda, desarrollado por la filial Nintendo EPD en colaboración con Monolith Soft y publicado por Nintendo para las consolas Wii U, Nintendo Switch, y Nintendo Switch 2',
                'price' => '95.00',
                'stock' => 50,
                'image_path' => 'products/OLmIQPQhzJBxKwCd3kaKVDEOwKwrx1WJmctQzfKe.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:25:50',
                'updated_at' => '2026-03-20 05:25:50',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'category_id' => 2,
                'name' => 'New Super Mario Bros',
                'slug' => 'new-super-mario-bros',
                'description' => 'New Super Mario Bros. Wii​ es un videojuego de plataformas desarrollado y publicado por Nintendo para la Wii. Se trata de la secuela de New Super Mario Bros. y salió a la venta en Australia, Norteamérica y Europa en noviembre de 2009, seguido de Japón un mes después.',
                'price' => '67.00',
                'stock' => 60,
                'image_path' => 'products/aCeyGxfkctnbLgJEVDQYMnQNTrmK8iZHAcPuj3Me.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:26:39',
                'updated_at' => '2026-03-20 13:15:23',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'category_id' => 4,
                'name' => 'FC 25',
                'slug' => 'fc-25',
                'description' => 'EA Sports FC 25 es un videojuego de fútbol, desarrollado por EA, y publicado por EA Sports. Es la segunda entrega de la serie EA Sports FC y la trigésimo segunda si se incluyen las entregas bajo el nombre de EA Sports FIFA, conocido popularmente como FIFA',
                'price' => '96.00',
                'stock' => 80,
                'image_path' => 'products/muMmXqxqy92Xz22RM7MWBsvmyhmUPTZTSXpCEsot.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:28:20',
                'updated_at' => '2026-03-20 13:15:23',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'category_id' => 1,
                'name' => 'Assassin\'s Creed IV: Black Flag',
                'slug' => 'assassins-creed-iv-black-flag',
                'description' => 'Assassin\'s Creed IV: Black Flag es un videojuego de acción y aventura y sigilo desarrollado por Ubisoft Montreal y publicado por Ubisoft. Es la sexta entrega principal de la serie Assassin\'s Creed.',
                'price' => '100.00',
                'stock' => 89,
                'image_path' => 'products/3j7dkk10pOqaaNl8J6swWIfBQeqFfrSLon6hIyp7.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:29:06',
                'updated_at' => '2026-03-20 05:29:06',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'category_id' => 3,
                'name' => 'Final Fantasy VII Rebirth',
                'slug' => 'final-fantasy-vii-rebirth',
                'description' => 'Final Fantasy VII Rebirth es un juego rol de acción, "juego por turnos y acción tiempo real", desarrollado y publicado por Square Enix. Es una secuela de Final Fantasy VII Remake y el segundo de una trilogía planificada de juegos que pretenden recrear el juego lanzado para PlayStation en 1997, Final Fantasy VII',
                'price' => '200.00',
                'stock' => 180,
                'image_path' => 'products/7IbY7JqCbwqKuDM6dfpiKYZp6w8a6SCZZL81lpPz.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:30:40',
                'updated_at' => '2026-03-20 05:30:40',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'category_id' => 5,
                'name' => 'Age of Empires',
                'slug' => 'age-of-empires',
                'description' => 'Age of Empires es una serie de videojuegos que, en su mayoría, pertenecen al género videojuego de estrategia en tiempo real, y hay otros juegos que pertenecen a otros géneros. La mayoría de los juegos son para la plataforma PC, y otros juegos son de otras plataformas.',
                'price' => '60.00',
                'stock' => 94,
                'image_path' => 'products/5sndDi3XN9qu5K2vXSOmEKuVzKcYBeVSYXDcWOHO.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:31:30',
                'updated_at' => '2026-03-20 05:31:30',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'category_id' => 7,
                'name' => 'Los Sims 4',
                'slug' => 'los-sims-4',
                'description' => 'Los Sims 4 es un videojuego de simulación social y de vida, el cuarto de la serie de juegos de Los Sims, desarrollado por Maxis y publicado por Electronic Arts para Windows y macOS',
                'price' => '90.00',
                'stock' => 155,
                'image_path' => 'products/xPSJHzdMMZwHNutvAqhZ1gRFA9EsecXWkFSJCaaF.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:32:49',
                'updated_at' => '2026-03-20 05:32:49',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'category_id' => 6,
                'name' => 'Backrooms',
                'slug' => 'backrooms',
                'description' => 'Los Backrooms son una leyenda urbana de internet y creepypasta que describe un laberinto infinito de oficinas vacías, moqueta húmeda y luces fluorescentes amarillas',
                'price' => '200.00',
                'stock' => 79,
                'image_path' => 'products/hxzdmtAZTg01KAzEezUCmWPJBDAtcUcbbXByFZ6A.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:34:12',
                'updated_at' => '2026-03-20 05:34:12',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'category_id' => 4,
                'name' => 'NBA 2k',
                'slug' => 'nba-2k',
                'description' => 'NBA 2K25 es un videojuego de baloncesto de 2024 desarrollado por Visual Concepts y publicado por 2K. Basado en la National Basketball Association, es la vigésimo sexta entrega de la serie NBA 2K y sucesor de NBA 2K24 y predecesor de NBA 2K26.',
                'price' => '90.00',
                'stock' => 100,
                'image_path' => 'products/KgUf2bsFn6lm9uWabtqJtU7AZZHkqWsI6bXmwVHX.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:37:45',
                'updated_at' => '2026-03-20 05:37:55',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'category_id' => 3,
                'name' => 'Pokémon rojo fuego',
                'slug' => 'pokemon-rojo-fuego',
                'description' => 'Pokémon Edición Rojo Fuego y Edición Verde Hoja, conocidos en Japón como Pocket Monsters Fire Red & Leaf Green, son dos videojuegos lanzados para la consola portátil Game Boy Advance de Nintendo en octubre de 2004, siendo remakes de los videojuegos Pokémon Rojo y Azul, lanzados en 1996',
                'price' => '200.00',
                'stock' => 125,
                'image_path' => 'products/1lFFSsSnwTkeqhF2YnVY7kzbzhtwwCQrgAHfyt5o.jpg',
                'is_active' => 1,
                'is_featured' => 1,
                'created_at' => '2026-03-20 05:38:47',
                'updated_at' => '2026-03-20 06:19:31',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'category_id' => 6,
                'name' => 'Poppy Playtime',
                'slug' => 'poppy-playtime',
                'description' => 'Poppy Playtime es un videojuego de terror y puzles desarrollado y publicado por la empresa MOB Entertainment',
                'price' => '310.00',
                'stock' => 599,
                'image_path' => 'products/Mirb40wx8zfwRPbllb7GSisF8QJqZ7y2eBt8Xrwb.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:40:06',
                'updated_at' => '2026-03-20 13:15:41',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'category_id' => 6,
                'name' => 'R.E.P.O.',
                'slug' => 'repo',
                'description' => 'R.E.P.O. es un videojuego de terror y supervivencia cooperativo en línea desarrollado y publicado por el estudio sueco Semiwork para Windows. Se lanzó en acceso anticipado el 26 de febrero de 2025 en Steam. Está desarrollado con el motor gráfico Unity.',
                'price' => '163.00',
                'stock' => 229,
                'image_path' => 'products/K3CgACWJLykK347yo1hBs0kFLV0PcO0Xkp0nhud9.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:40:48',
                'updated_at' => '2026-03-20 13:15:41',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'category_id' => 3,
                'name' => 'Warcraft III: The Frozen Throne',
                'slug' => 'warcraft-iii-the-frozen-throne',
                'description' => 'Warcraft: The Frozen Throne es un videojuego de estrategia en tiempo real y expansión de Warcraft III: Reign of Chaos desarrollado por Blizzard Entertainment. La instalación de Warcraft III: Reign of Chaos es necesaria para poder jugar a esta expansión',
                'price' => '145.00',
                'stock' => 239,
                'image_path' => 'products/xHzX4lXe41uZKawXTxq7zmVTriejWD7SbxR9aSf1.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:41:56',
                'updated_at' => '2026-03-20 13:23:25',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'category_id' => 2,
                'name' => 'Hitman',
                'slug' => 'hitman',
                'description' => 'Hitman es una serie de videojuegos de sigilo disponible en la mayoría de los formatos modernos. La trama de los videojuegos gira en torno a un hombre llamado Agente 47, que es el producto de experimentos de mejoras genéticas y creación de superhombres, especialmente diseñado para asesinar cuando se lo contrata.',
                'price' => '125.00',
                'stock' => 209,
                'image_path' => 'products/eAeDk8R5Obl6t3DzqLJndTymlWATmJrL6Z6HYUgZ.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:42:44',
                'updated_at' => '2026-03-20 13:23:25',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'category_id' => 5,
                'name' => 'Ludo Club: Divertido juego',
                'slug' => 'ludo-club-divertido-juego',
                'description' => 'Juega Ludo en línea con tus amigos y conviértete en una estrella: ¡juega LUDO CLUB! ¡Esta es la versión multijugador en línea de Ludo, el juego épico!',
                'price' => '40.00',
                'stock' => 199,
                'image_path' => 'products/oQYbcjc0Wd0uIzT0ZCCW8j2L6NAbEpCz5ocVNmhc.jpg',
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:47:04',
                'updated_at' => '2026-03-25 03:27:02',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'category_id' => 2,
                'name' => 'Test',
                'slug' => 'test',
                'description' => 'Probar',
                'price' => '21.00',
                'stock' => 21,
                'image_path' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'created_at' => '2026-03-20 05:47:29',
                'updated_at' => '2026-03-20 05:52:24',
                'deleted_at' => '2026-03-20 05:52:24',
            ),
        ));
        
        
    }
}